<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>stats506_ps2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="stats506_ps2_files/libs/clipboard/clipboard.min.js"></script>
<script src="stats506_ps2_files/libs/quarto-html/quarto.js"></script>
<script src="stats506_ps2_files/libs/quarto-html/popper.min.js"></script>
<script src="stats506_ps2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="stats506_ps2_files/libs/quarto-html/anchor.min.js"></script>
<link href="stats506_ps2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="stats506_ps2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="stats506_ps2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="stats506_ps2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="stats506_ps2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">stats506_ps2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="problem-1---dice-game" class="level2">
<h2 class="anchored" data-anchor-id="problem-1---dice-game"><strong>Problem 1 - Dice Game</strong></h2>
<p>Let's play a dice game. It costs $2 to play. You roll a single 6-sided die.</p>
<ul>
<li><p>On a roll of 2, 4, or 6, you win the amount on the roll (e.g.&nbsp;a roll of 4 wins $4).</p></li>
<li><p>On a roll of 1, 3, or 5, you lose.</p></li>
</ul>
<p>We're going to implement this in different ways. Each function takes in as input the number of dice to roll, and each function returns your total winnings or loses.</p>
<p>a.</p>
<ul>
<li><p>Version 1: Implement this game using a loop over the die rolls.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#' A function to identify the amount of winnings (or losses) when you play a dice game that costs $2 to play. In this game, you roll a single 6-sided die. On a roll of 2, 4, or 6, you win the amount on the roll (e.g. a roll of 4 wins $4). On a roll of 1, 3, or 5, you lose.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#' </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param number_dice_to_roll is the number of dice you roll </span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return your total earnings</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#' @examples </span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice(2)</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice(10)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>play_dice <span class="ot">&lt;-</span> <span class="cf">function</span>(number_dice_to_roll){</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  total_earnings <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>number_dice_to_roll){</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    roll <span class="ot">=</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(roll <span class="sc">==</span> <span class="dv">2</span><span class="sc">|</span> roll <span class="sc">==</span> <span class="dv">4</span> <span class="sc">|</span> roll <span class="sc">==</span> <span class="dv">6</span>){</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>      winning <span class="ot">=</span> roll</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>      total_earnings <span class="ot">=</span> total_earnings <span class="sc">+</span> roll</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    }<span class="cf">else</span>{</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>      total_earnings <span class="ot">=</span> total_earnings <span class="sc">-</span> <span class="dv">2</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(total_earnings)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>Version 2: Implement this game using built-in R vectorized functions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#' A function to identify the amount of winnings (or losses) when you play a dice game that costs $2 to play. In this game, you roll a single 6-sided die. On a roll of 2, 4, or 6, you win the amount on the roll (e.g. a roll of 4 wins $4). On a roll of 1, 3, or 5, you lose.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#' </span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param number_dice_to_roll_2 is the number of dice you roll </span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return your total earnings</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#' @examples </span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_2(2)</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_2(10)</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>play_dice_2 <span class="ot">&lt;-</span> <span class="cf">function</span>(number_dice_to_roll_2){</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  sample_2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> number_dice_to_roll_2, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  total_earnings_2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(sample_2[sample_2 <span class="sc">%%</span> <span class="dv">2</span> <span class="sc">==</span> <span class="dv">0</span>]) <span class="sc">-</span> (<span class="dv">2</span><span class="sc">*</span>(<span class="fu">length</span>(sample_2[sample_2 <span class="sc">%%</span> <span class="dv">2</span> <span class="sc">!=</span> <span class="dv">0</span>])))</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(total_earnings_2)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>Version 3: Implement this by collapsing the die rolls into a single&nbsp;<code>table()</code>. (Hint: Be careful indexing the table - what happens if you make a table of 5 dice rolls? You may need to look to other resources for how to solve this.)</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#' A function to identify the amount of winnings (or losses) when you play a dice game that costs $2 to play. In this game, you roll a single 6-sided die. On a roll of 2, 4, or 6, you win the amount on the roll (e.g. a roll of 4 wins $4). On a roll of 1, 3, or 5, you lose.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#' </span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param number_dice_to_roll_3 is the number of dice you roll </span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return your total earnings</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#' @examples </span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_3(2)</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_3(10)</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>play_dice_3 <span class="ot">&lt;-</span> <span class="cf">function</span>(number_dice_to_roll_3){</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  sample_3 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> number_dice_to_roll_3, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  sample_3_table <span class="ot">&lt;-</span> <span class="fu">table</span>(sample_3)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(data.table)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  sample_3_df <span class="ot">&lt;-</span> <span class="fu">data.table</span>(sample_3_table)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  sample_3_df<span class="sc">$</span>sample_3 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(sample_3_df<span class="sc">$</span>sample_3)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  sample_3_df<span class="sc">$</span>type <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sample_3_df<span class="sc">$</span>sample_3 <span class="sc">%%</span> <span class="dv">2</span> <span class="sc">==</span> <span class="dv">0</span>, <span class="st">"even"</span>, <span class="st">"odd"</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  sample_3_df<span class="sc">$</span>earning <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sample_3_df<span class="sc">$</span>type <span class="sc">==</span> <span class="st">"even"</span>, sample_3_df<span class="sc">$</span>sample_3 <span class="sc">*</span> sample_3_df<span class="sc">$</span>N, sample_3_df<span class="sc">$</span>N <span class="sc">*</span> <span class="sc">-</span><span class="dv">2</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>((<span class="fu">sum</span>(sample_3_df<span class="sc">$</span>earning)))</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Version 4: Implement this game by using one of the "<code>apply</code>" functions.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#' A function to identify the amount of winnings (or losses) when you play a dice game that costs $2 to play. In this game, you roll a single 6-sided die. On a roll of 2, 4, or 6, you win the amount on the roll (e.g. a roll of 4 wins $4). On a roll of 1, 3, or 5, you lose.</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#' </span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param number_dice_to_roll_4 is the number of dice you roll </span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return your total earnings</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co">#' @examples </span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_4(2)</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_4(10)</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>play_dice_4 <span class="ot">&lt;-</span> <span class="cf">function</span>(number_dice_to_roll_4){</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  sample_4 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> number_dice_to_roll_4, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  evens <span class="ot">&lt;-</span> sample_4[<span class="fu">lapply</span>(sample_4, <span class="st">'%%'</span>, <span class="dv">2</span>) <span class="sc">==</span> <span class="dv">0</span>] <span class="co"># Q1: why do I need to separate the modulus and the 2 like this?; COMMENT: https://stackoverflow.com/questions/61484767/function-for-selecting-even-numbers-in-a-vector-in-r helped me</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  odds <span class="ot">&lt;-</span> sample_4[<span class="fu">lapply</span>(sample_4, <span class="st">'%%'</span>, <span class="dv">2</span>) <span class="sc">!=</span> <span class="dv">0</span>]</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  total_earnings <span class="ot">&lt;-</span> (<span class="fu">sum</span>(evens)) <span class="sc">-</span>  ((<span class="dv">2</span>)<span class="sc">*</span>(<span class="fu">length</span>(odds)))</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(total_earnings)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="a">
<li><p>Demonstrate that all versions work. Do so by running each a few times, once with an input a 3, and once with an input of 3000.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice</span>(<span class="dv">3000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2890</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_2</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_2</span>(<span class="dv">3000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3154</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_3</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_3</span>(<span class="dv">3000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3130</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_4</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_4</span>(<span class="dv">3000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2758</code></pre>
</div>
</div></li>
<li><p>Demonstrate that the four versions give the same result. Test with inputs 3 and 3000. (You may need to add a way to control the randomization.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#' A function to identify the amount of winnings (or losses) when you play a dice game that costs $2 to play. In this game, you roll a single 6-sided die. On a roll of 2, 4, or 6, you win the amount on the roll (e.g. a roll of 4 wins $4). On a roll of 1, 3, or 5, you lose. I note that the seed has been set at 5 for the sample generator in this function to ensure that we can check the results across multiple functions.</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co">#' </span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param number_dice_to_roll is the number of dice you roll </span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return your total earnings</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co">#' @examples </span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice(2)</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice(10)</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>play_dice <span class="ot">&lt;-</span> <span class="cf">function</span>(number_dice_to_roll){</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  total_earnings <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">5</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>number_dice_to_roll){</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    roll <span class="ot">=</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(roll <span class="sc">==</span> <span class="dv">2</span><span class="sc">|</span> roll <span class="sc">==</span> <span class="dv">4</span> <span class="sc">|</span> roll <span class="sc">==</span> <span class="dv">6</span>){</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>      winning <span class="ot">=</span> roll</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>      total_earnings <span class="ot">=</span> total_earnings <span class="sc">+</span> roll</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    }<span class="cf">else</span>{</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>      total_earnings <span class="ot">=</span> total_earnings <span class="sc">-</span> <span class="dv">2</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(total_earnings)</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a><span class="co">#' A function to identify the amount of winnings (or losses) when you play a dice game that costs $2 to play. In this game, you roll a single 6-sided die. On a roll of 2, 4, or 6, you win the amount on the roll (e.g. a roll of 4 wins $4). On a roll of 1, 3, or 5, you lose. I note that the seed has been set at 5 for the sample generator in this function to ensure that we can check the results across multiple functions.</span></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a><span class="co">#' </span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param number_dice_to_roll_2 is the number of dice you roll </span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return your total earnings</span></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a><span class="co">#' @examples </span></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_2(2)</span></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_2(10)</span></span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>play_dice_2 <span class="ot">&lt;-</span> <span class="cf">function</span>(number_dice_to_roll_2){</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">5</span>)</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>  sample_2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> number_dice_to_roll_2, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>  total_earnings_2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(sample_2[sample_2 <span class="sc">%%</span> <span class="dv">2</span> <span class="sc">==</span> <span class="dv">0</span>]) <span class="sc">-</span> (<span class="dv">2</span><span class="sc">*</span>(<span class="fu">length</span>(sample_2[sample_2 <span class="sc">%%</span> <span class="dv">2</span> <span class="sc">!=</span> <span class="dv">0</span>])))</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(total_earnings_2)</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a><span class="co">#' A function to identify the amount of winnings (or losses) when you play a dice game that costs $2 to play. In this game, you roll a single 6-sided die. On a roll of 2, 4, or 6, you win the amount on the roll (e.g. a roll of 4 wins $4). On a roll of 1, 3, or 5, you lose. I note that the seed has been set at 5 for the sample generator in this function to ensure that we can check the results across multiple functions.</span></span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a><span class="co">#' </span></span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param number_dice_to_roll_3 is the number of dice you roll </span></span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return your total earnings</span></span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a><span class="co">#' @examples </span></span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_3(2)</span></span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_3(10)</span></span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a>play_dice_3 <span class="ot">&lt;-</span> <span class="cf">function</span>(number_dice_to_roll_3){</span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">5</span>)</span>
<span id="cb21-46"><a href="#cb21-46" aria-hidden="true" tabindex="-1"></a>  sample_3 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> number_dice_to_roll_3, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-47"><a href="#cb21-47" aria-hidden="true" tabindex="-1"></a>  sample_3_table <span class="ot">&lt;-</span> <span class="fu">table</span>(sample_3)</span>
<span id="cb21-48"><a href="#cb21-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(data.table)</span>
<span id="cb21-49"><a href="#cb21-49" aria-hidden="true" tabindex="-1"></a>  sample_3_df <span class="ot">&lt;-</span> <span class="fu">data.table</span>(sample_3_table)</span>
<span id="cb21-50"><a href="#cb21-50" aria-hidden="true" tabindex="-1"></a>  sample_3_df<span class="sc">$</span>sample_3 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(sample_3_df<span class="sc">$</span>sample_3)</span>
<span id="cb21-51"><a href="#cb21-51" aria-hidden="true" tabindex="-1"></a>  sample_3_df<span class="sc">$</span>type <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sample_3_df<span class="sc">$</span>sample_3 <span class="sc">%%</span> <span class="dv">2</span> <span class="sc">==</span> <span class="dv">0</span>, <span class="st">"even"</span>, <span class="st">"odd"</span>)</span>
<span id="cb21-52"><a href="#cb21-52" aria-hidden="true" tabindex="-1"></a>  sample_3_df<span class="sc">$</span>earning <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sample_3_df<span class="sc">$</span>type <span class="sc">==</span> <span class="st">"even"</span>, sample_3_df<span class="sc">$</span>sample_3 <span class="sc">*</span> sample_3_df<span class="sc">$</span>N, sample_3_df<span class="sc">$</span>N <span class="sc">*</span> <span class="sc">-</span><span class="dv">2</span>)</span>
<span id="cb21-53"><a href="#cb21-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>((<span class="fu">sum</span>(sample_3_df<span class="sc">$</span>earning)))</span>
<span id="cb21-54"><a href="#cb21-54" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-55"><a href="#cb21-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-56"><a href="#cb21-56" aria-hidden="true" tabindex="-1"></a><span class="co">#' A function to identify the amount of winnings (or losses) when you play a dice game that costs $2 to play. In this game, you roll a single 6-sided die. On a roll of 2, 4, or 6, you win the amount on the roll (e.g. a roll of 4 wins $4). On a roll of 1, 3, or 5, you lose. I note that the seed has been set at 5 for the sample generator in this function to ensure that we can check the results across multiple functions.</span></span>
<span id="cb21-57"><a href="#cb21-57" aria-hidden="true" tabindex="-1"></a><span class="co">#' </span></span>
<span id="cb21-58"><a href="#cb21-58" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param number_dice_to_roll_4 is the number of dice you roll </span></span>
<span id="cb21-59"><a href="#cb21-59" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return your total earnings</span></span>
<span id="cb21-60"><a href="#cb21-60" aria-hidden="true" tabindex="-1"></a><span class="co">#' @examples </span></span>
<span id="cb21-61"><a href="#cb21-61" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_4(2)</span></span>
<span id="cb21-62"><a href="#cb21-62" aria-hidden="true" tabindex="-1"></a><span class="co">#' play_dice_4(10)</span></span>
<span id="cb21-63"><a href="#cb21-63" aria-hidden="true" tabindex="-1"></a>play_dice_4 <span class="ot">&lt;-</span> <span class="cf">function</span>(number_dice_to_roll_4){</span>
<span id="cb21-64"><a href="#cb21-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">5</span>)</span>
<span id="cb21-65"><a href="#cb21-65" aria-hidden="true" tabindex="-1"></a>  sample_4 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> number_dice_to_roll_4, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-66"><a href="#cb21-66" aria-hidden="true" tabindex="-1"></a>  evens <span class="ot">&lt;-</span> sample_4[<span class="fu">lapply</span>(sample_4, <span class="st">'%%'</span>, <span class="dv">2</span>) <span class="sc">==</span> <span class="dv">0</span>] <span class="co"># Q1: why do I need to separate the modulus and the 2 like this?; COMMENT: https://stackoverflow.com/questions/61484767/function-for-selecting-even-numbers-in-a-vector-in-r helped me</span></span>
<span id="cb21-67"><a href="#cb21-67" aria-hidden="true" tabindex="-1"></a>  odds <span class="ot">&lt;-</span> sample_4[<span class="fu">lapply</span>(sample_4, <span class="st">'%%'</span>, <span class="dv">2</span>) <span class="sc">!=</span> <span class="dv">0</span>]</span>
<span id="cb21-68"><a href="#cb21-68" aria-hidden="true" tabindex="-1"></a>  total_earnings <span class="ot">&lt;-</span> (<span class="fu">sum</span>(evens)) <span class="sc">-</span>  ((<span class="dv">2</span>)<span class="sc">*</span>(<span class="fu">length</span>(odds)))</span>
<span id="cb21-69"><a href="#cb21-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(total_earnings)</span>
<span id="cb21-70"><a href="#cb21-70" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice</span>(<span class="dv">3000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2830</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_2</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_2</span>(<span class="dv">3000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2830</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_3</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_3</span>(<span class="dv">3000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2830</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_4</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">play_dice_4</span>(<span class="dv">3000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2830</code></pre>
</div>
</div></li>
<li><p>Use the&nbsp;<em>microbenchmark</em>&nbsp;package to clearly demonstrate the speed of the implementations. Compare performance with a low input (100) and a large input (10000). Discuss the results</p></li>
</ol>
<pre><code>::: {.cell}

```{.r .cell-code}
library(microbenchmark)
microbenchmark(play_dice(100), play_dice_2(100), play_dice_3(100), play_dice_4(100))
```

::: {.cell-output .cell-output-stderr}
```
Warning in microbenchmark(play_dice(100), play_dice_2(100), play_dice_3(100), :
less accurate nanosecond times to avoid potential integer overflows
```
:::

::: {.cell-output .cell-output-stdout}
```
Unit: microseconds
             expr     min       lq      mean   median       uq      max neval
   play_dice(100) 267.115 283.4535 349.45366 295.5895 306.5775 3224.568   100
 play_dice_2(100)   8.282   9.0610  10.83425  10.4140  11.7055   21.402   100
 play_dice_3(100) 306.270 316.6840 360.62288 333.5760 371.9930  616.107   100
 play_dice_4(100)  41.123  43.5830  47.32917  45.5510  49.6510   64.042   100
```
:::
:::


According to Hadley Wickham, when looking at the measurement of performance as provided by `microbenchmark`, we should focus on the median and use the upper and lower quartiles to get a feel for the variability. Looking at the median, we see that the function I wrote that involves the table is the slowest. That is probably because I converted my table to a dataframe to do the final sum. Next is the for loop, which given our discussion in class, I would definitely expect to be the slowest. Again, I think that the table function turned out to be slowest because of my use of the dataframe. Next, we have the `apply` function (and specifically `lapply`). As noted in the lecture notes, `lapply` actually drops down to C for its loops, and at each step in the C loop, it evaluates the R function passed in. This is what makes it not vectorized, as a true vectorized function performs its loop in C \emph{and} uses C compiled functions inside that loop. With that explanation in mind, it is not surprising that my version of the function that uses `lapply` is slower than the vectorized version. Finally, the vectorized version (`play_dice_2`) is the fastest. I note that this explanation was for the case with the low input (100). Let's see what happens when we use the large input (10000).


::: {.cell}

```{.r .cell-code}
microbenchmark(play_dice(10000), play_dice_2(10000), play_dice_3(10000), play_dice_4(10000))
```

::: {.cell-output .cell-output-stdout}
```
Unit: microseconds
               expr       min         lq       mean    median        uq
   play_dice(10000) 29583.878 30863.3445 32089.5061 31452.494 32818.696
 play_dice_2(10000)   394.871   415.9040   432.2282   426.031   439.274
 play_dice_3(10000)   861.779   934.2465  1072.9827  1100.666  1177.171
 play_dice_4(10000)  3418.047  3595.4335  4176.1042  3729.914  4070.111
       max neval
 51798.826   100
   536.854   100
  1331.024   100
  6550.447   100
```
:::
:::


I noticed a few things here. First, it took a significantly longer time to get through the functions. That just emphasizes that these nanoseconds add up when the numbers get larger. Second, the loop function (`play_dice`) is SO much slower than every other function - even the next slowest (`play_dice_4`), it is slower by about 10 orders of magnitude. Wow. It is interesting that the `lapply` function (`play_dice_4`) took a big hit on speed when we ramped the numbers up. This is clearly the effect of the underlying loops being run over and over again with this function. The table function (`play_dice_3`) had significant gains this time. This suggests to me that while it was slow to set up the dataframe, once it was there, it was faster than going through with something like a loop. Lastly, (and still), the vectorized option is still the fastest.</code></pre>
<ol start="5" type="a">
<li><p>Do you think this is a fair game? Defend your decision with evidence based upon a Monte Carlo simulation.</p>
<p>I note that if the dice is fair, the probability of any one digit appearing on a single roll is <span class="math inline">\(1/6\)</span> and the probability of that digit appearing is <span class="math inline">\(1 - 1/6 = 5/6\)</span>. Because we are assuming that these rolls are independent (i.e.&nbsp;with replacement), any one of the numbers should not appear more than <span class="math inline">\(5/6^n\)</span> where <span class="math inline">\(n\)</span> is the number of rolls. To test whether the die is “fair” we can compare this theoretical result to the actual result above where I <code>set.seed(5)</code> and <code>sample(x = 1:6, size = number_dice_to_roll, replace = TRUE)</code>. I note that I used this site to help me with this answer: https://stackoverflow.com/questions/41685557/estimate-the-chance-n-rolls-of-m-fair-six-sided-dice.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fair_dice <span class="ot">&lt;-</span> <span class="cf">function</span>(number_of_rolls){</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">5</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">replicate</span>(number_of_rolls, <span class="dv">1</span> <span class="sc">%in%</span> <span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Compare to a theoretical result.</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  theory <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span>(<span class="dv">5</span><span class="sc">/</span><span class="dv">6</span>)<span class="sc">^</span>(number_of_rolls)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  avg <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  Z <span class="ot">&lt;-</span> (avg <span class="sc">-</span> theory) <span class="sc">/</span> <span class="fu">sd</span>(x) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(x))</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  p_value <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(Z, avg, <span class="fu">sd</span>(x))</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">cat</span>(<span class="st">"Z-score:"</span>, Z, <span class="st">"</span><span class="sc">\n</span><span class="st"> p-value:"</span>, p_value))</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="fu">fair_dice</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z-score: -3.525273 
 p-value: 1.196483e-15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fair_dice</span>(<span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z-score: -21.98529 
 p-value: 0</code></pre>
</div>
</div></li>
</ol>
<p>This result suggests to us that the die is indeed fair, with such a low p-value both with a low number of rolls at <span class="math inline">\(10\)</span> and a p-value of <span class="math inline">\(1.196483 \cdot 10^{-15}\)</span> and with a higher number of rolls at <span class="math inline">\(100\)</span> with a p-value that is effectively <span class="math inline">\(0\)</span>.</p>
</section>
<section id="problem-2---linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="problem-2---linear-regression">Problem 2 - Linear Regression</h2>
<p>Download the cars data set available at&nbsp;<a href="https://corgis-edu.github.io/corgis/csv/cars/" class="uri">https://corgis-edu.github.io/corgis/csv/cars/</a>. The goal is to examine the relationship between horsepower and highway gas mileage.</p>
<p>a. The names of the variables in this data are way too long. Rename the columns of the data to more reasonable lengths.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:data.table':

    between, first, last</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>cars <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'/Users/dereklief/Desktop/MAIN FOLDER/Classes and Other/STATS 506/PS 2/stats506_ps2/cars.csv'</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>cars <span class="ot">&lt;-</span> cars <span class="sc">%&gt;%</span> <span class="co">#Q2 for Josh: is there a faster/better way to do this?</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">rename</span>(<span class="at">height =</span> <span class="dv">1</span>, </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">length =</span> <span class="dv">2</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">width =</span> <span class="dv">3</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">driveline =</span> <span class="dv">4</span>,</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">engine_type =</span> <span class="dv">5</span>,</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">hybrid =</span> <span class="dv">6</span>,</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">no_fwd_gears =</span> <span class="dv">7</span>,</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">transmission =</span> <span class="dv">8</span>,</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">city_mpg =</span> <span class="dv">9</span>,</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">fuel_type =</span> <span class="dv">10</span>,</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">highway_mpg =</span> <span class="dv">11</span>,</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>              <span class="at">classification =</span> <span class="dv">12</span>,</span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>              <span class="at">id =</span> <span class="dv">13</span>,</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>              <span class="at">make =</span> <span class="dv">14</span>,</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>              <span class="at">model_year =</span> <span class="dv">15</span>,</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>              <span class="at">year =</span> <span class="dv">16</span>,</span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>              <span class="at">horsepower =</span> <span class="dv">17</span>,</span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>              <span class="at">torque =</span> <span class="dv">18</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>b. Restrict the data to cars whose Fuel Type is "Gasoline".</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>gas_cars <span class="ot">&lt;-</span> cars[cars<span class="sc">$</span>fuel_type <span class="sc">==</span> <span class="st">"Gasoline"</span>, ]</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(gas_cars<span class="sc">$</span>fuel_type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Gasoline 
    4591 </code></pre>
</div>
</div>
<p>c. Fit a linear regression model predicting MPG on the highway. The predictor of interest is horsepower. Control for:</p>
<ul>
<li><p>The torque of the engine</p></li>
<li><p>All three dimensions of the car</p></li>
<li><p>The year the measurement was made, as a categorical variable. (Not the year the car was manufactured.)</p></li>
</ul>
<p>Briefly discuss the estimated relationship between horsepower and highway MPG. Be precise about the interpretation of the estimated coefficient.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>gas_cars<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(gas_cars<span class="sc">$</span>year)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(highway_mpg <span class="sc">~</span> horsepower <span class="sc">+</span> torque <span class="sc">+</span> height <span class="sc">+</span> length <span class="sc">+</span> width <span class="sc">+</span> year, <span class="at">data =</span> gas_cars)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = highway_mpg ~ horsepower + torque + height + length + 
    width + year, data = gas_cars)

Residuals:
    Min      1Q  Median      3Q     Max 
-10.824  -2.550  -0.452   2.372 202.639 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 32.2926630  0.7225982  44.690  &lt; 2e-16 ***
horsepower   0.0163556  0.0022772   7.182 7.96e-13 ***
torque      -0.0507425  0.0022030 -23.034  &lt; 2e-16 ***
height       0.0099079  0.0011267   8.794  &lt; 2e-16 ***
length       0.0017290  0.0008836   1.957   0.0504 .  
width       -0.0003343  0.0009045  -0.370   0.7117    
year2010    -0.4539681  0.6768246  -0.671   0.5024    
year2011     0.1711016  0.6757043   0.253   0.8001    
year2012     1.3029279  0.6810076   1.913   0.0558 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.602 on 4582 degrees of freedom
Multiple R-squared:  0.4192,    Adjusted R-squared:  0.4182 
F-statistic: 413.3 on 8 and 4582 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The summary statistics from our model, <code>m1</code> above show that there is a positive, statistically significant association between <code>horsepower</code> and <code>MPG</code> controlling for <code>torque</code>, <code>height</code>, <code>length</code>, <code>width</code> and <code>year</code>. I note that some may interpret these results as “for every 1 unit increase in horsepower, there is a 0.016 unit increase in highway MPG, and that the relationship is statistically significant at the 0.01 level.” This claim, in quotations, however, implies causality, which is not something we can determine from <code>m1</code>. The best we can do is correlation, which is why I used the word “association” in the beginning.</p>
<p>d. It seems reasonable that there may be an interaction between horsepower and torque. Refit the model (with&nbsp;<code>lm</code>) and generate an interaction plot, showing how the relationship between horsepower and MPG changes as torque changes. Choose reasonable values of horsepower, and show lines for three different reasonable values of torque.</p>
<p>We know that torque and horsepower are continuous variables. To find a reasonable range for horsepower, and a reasonable way to segment torque into three lines, let’s look at summaries of their values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gas_cars<span class="sc">$</span>horsepower)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  100.0   185.0   263.0   267.5   317.0   638.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gas_cars<span class="sc">$</span>torque)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   98.0   177.0   257.0   267.2   332.0   774.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gas_cars<span class="sc">$</span>year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2009 2010 2011 2012 
  48 1633 1794 1116 </code></pre>
</div>
</div>
<p>OK, so for horsepower, we can set our x-axis to values between <span class="math inline">\(100\)</span> and $638$, and for torque, it makes sense to set “low”, “medium” and “high” (0, 1, 2) for values between $98 - 176.99999$, <span class="math inline">\(177 - 331.999999\)</span> and <span class="math inline">\(332 - 774\)</span>, respectively.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>gas_cars<span class="sc">$</span>torque_level <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(gas_cars<span class="sc">$</span>torque <span class="sc">&lt;</span> <span class="dv">177</span>, <span class="st">"low"</span>,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">ifelse</span>(gas_cars<span class="sc">$</span>torque <span class="sc">&gt;=</span> <span class="dv">177</span> <span class="sc">&amp;</span> gas_cars<span class="sc">$</span>torque <span class="sc">&lt;</span> <span class="dv">332</span>, <span class="st">"medium"</span>, <span class="st">"high"</span>)) </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>gas_cars<span class="sc">$</span>torque_level <span class="ot">&lt;-</span> <span class="fu">factor</span>(gas_cars<span class="sc">$</span>torque_level, <span class="at">level =</span> <span class="fu">c</span>(<span class="st">"low"</span>, <span class="st">"medium"</span>, <span class="st">"high"</span>))</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gas_cars<span class="sc">$</span>torque_level)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] medium medium medium medium medium medium
Levels: low medium high</code></pre>
</div>
</div>
<p>Now, let’s run our model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(highway_mpg <span class="sc">~</span> (horsepower<span class="sc">*</span>torque_level) <span class="sc">+</span> height <span class="sc">+</span> length <span class="sc">+</span> width <span class="sc">+</span> <span class="fu">as.factor</span>(year), <span class="at">data =</span> gas_cars)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = highway_mpg ~ (horsepower * torque_level) + height + 
    length + width + as.factor(year), data = gas_cars)

Residuals:
    Min      1Q  Median      3Q     Max 
 -9.934  -2.401  -0.195   2.304 203.322 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    4.387e+01  1.169e+00  37.518  &lt; 2e-16 ***
horsepower                    -8.439e-02  5.627e-03 -14.996  &lt; 2e-16 ***
torque_levelmedium            -1.461e+01  1.028e+00 -14.209  &lt; 2e-16 ***
torque_levelhigh              -2.317e+01  1.131e+00 -20.490  &lt; 2e-16 ***
height                         6.483e-03  1.119e-03   5.795 7.28e-09 ***
length                         6.472e-04  8.626e-04   0.750    0.453    
width                         -4.856e-03  9.119e-04  -5.325 1.06e-07 ***
as.factor(year)2010           -9.268e-01  6.604e-01  -1.403    0.161    
as.factor(year)2011           -2.617e-01  6.594e-01  -0.397    0.692    
as.factor(year)2012            1.067e+00  6.646e-01   1.605    0.108    
horsepower:torque_levelmedium  6.480e-02  5.924e-03  10.939  &lt; 2e-16 ***
horsepower:torque_levelhigh    8.361e-02  5.846e-03  14.303  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.488 on 4579 degrees of freedom
Multiple R-squared:  0.448, Adjusted R-squared:  0.4467 
F-statistic: 337.9 on 11 and 4579 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Now we want to produce an interaction plot, but the hint tells us to simplify the problem by choosing just one year. Let’s see how many observations are in each year to choose a reasonable year:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(gas_cars<span class="sc">$</span>year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
2009 2010 2011 2012 
  48 1633 1794 1116 </code></pre>
</div>
</div>
<p>We could reasonable choose any of the years from $2010 - 2012$, but since <span class="math inline">\(2011\)</span> has the most observations, let’s choose that year:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>gas_cars_2011 <span class="ot">&lt;-</span> gas_cars[ <span class="fu">which</span>(gas_cars<span class="sc">$</span>year<span class="sc">==</span><span class="dv">2011</span>), ]</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(highway_mpg <span class="sc">~</span> (horsepower<span class="sc">*</span>torque_level) <span class="sc">+</span> height <span class="sc">+</span> length <span class="sc">+</span> width, <span class="at">data =</span> gas_cars_2011)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = highway_mpg ~ (horsepower * torque_level) + height + 
    length + width, data = gas_cars_2011)

Residuals:
    Min      1Q  Median      3Q     Max 
 -9.731  -2.345  -0.224   2.194 202.721 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    43.621168   2.023491  21.557  &lt; 2e-16 ***
horsepower                     -0.085491   0.011607  -7.365 2.68e-13 ***
torque_levelmedium            -15.725715   2.135139  -7.365 2.69e-13 ***
torque_levelhigh              -21.093957   2.351654  -8.970  &lt; 2e-16 ***
height                          0.005608   0.002335   2.401  0.01643 *  
length                          0.002386   0.001812   1.317  0.18812    
width                          -0.006404   0.001964  -3.261  0.00113 ** 
horsepower:torque_levelmedium   0.070410   0.012248   5.748 1.06e-08 ***
horsepower:torque_levelhigh     0.080477   0.012075   6.665 3.52e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.892 on 1785 degrees of freedom
Multiple R-squared:  0.2968,    Adjusted R-squared:  0.2936 
F-statistic: 94.16 on 8 and 1785 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmip</span>(m3, <span class="fu">as.factor</span>(torque_level) <span class="sc">~</span> horsepower, <span class="at">at =</span> <span class="fu">list</span>(<span class="at">horsepower =</span> <span class="dv">100</span><span class="sc">:</span><span class="dv">638</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats506_ps2_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Q3: how to change order of torque level?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Just for fun, I want to try this with <code>interact_plot</code> too:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(m3, <span class="at">pred =</span> horsepower, <span class="at">modx =</span> torque_level)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats506_ps2_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>e. Calculate <span class="math inline">\(\hat{\beta}\)</span> manually (without using&nbsp;<code>lm</code>) by first creating a proper design matrix, then using matrix algebra to estimate <span class="math inline">\(\beta\)</span>. Confirm that you get the same result as&nbsp;<code>lm</code>&nbsp;did prior.</p>
<p>Let’s try and do this for each of our three models above, starting with <code>m1</code>. I note that I am going to be very deliberate here so everything is clear:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(m1, <span class="at">data =</span> gas_cars) <span class="co"># step 1: define our design matrix, X</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>X_trans <span class="ot">&lt;-</span> <span class="fu">t</span>(X) <span class="co"># step 2: based on our design matrix, define X^t</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>X_2 <span class="ot">&lt;-</span> X_trans <span class="sc">%*%</span> X <span class="co"># step 3: multiply X^t by our design matrix</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>X_inv <span class="ot">&lt;-</span> <span class="fu">solve</span>(X_2) <span class="co"># step 4: take the inverse of X^t and X</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> gas_cars<span class="sc">$</span>highway_mpg <span class="co">#step 5: define y</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="ot">&lt;-</span> (X_inv <span class="sc">%*%</span> X_trans) <span class="sc">%*%</span> y <span class="co"># step 6: calculate beta hat, which will be a vector of our coefficients (and intercept)</span></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>beta_hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     [,1]
(Intercept) 32.2926630057
horsepower   0.0163556341
torque      -0.0507424622
height       0.0099078942
length       0.0017289759
width       -0.0003343217
year2010    -0.4539681241
year2011     0.1711016371
year2012     1.3029279007</code></pre>
</div>
</div>
<p>If we look back up to <span class="math inline">\(2c\)</span>, we see that the intercept and coefficients that we get here are identical to what we got in that problem. Now let’s do the same for <code>m2</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>X_m2 <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(m2, <span class="at">data =</span> gas_cars) <span class="co"># step 1: define our design matrix, X</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>X_m2_trans <span class="ot">&lt;-</span> <span class="fu">t</span>(X_m2) <span class="co"># step 2: based on our design matrix, define X^t</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>X_m2_2 <span class="ot">&lt;-</span> X_m2_trans <span class="sc">%*%</span> X_m2 <span class="co"># step 3: multiply X^t by our design matrix</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>X_m2_inv <span class="ot">&lt;-</span> <span class="fu">solve</span>(X_m2_2) <span class="co"># step 4: take the inverse of X^t and X</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>beta_hat_m2 <span class="ot">&lt;-</span> (X_m2_inv <span class="sc">%*%</span> X_m2_trans) <span class="sc">%*%</span> y <span class="co"># step 6: calculate beta hat, which will be a vector of our coefficients (and intercept)</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>beta_hat_m2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                       [,1]
(Intercept)                    4.386863e+01
horsepower                    -8.438740e-02
torque_levelmedium            -1.461120e+01
torque_levelhigh              -2.317137e+01
height                         6.483264e-03
length                         6.471658e-04
width                         -4.855895e-03
as.factor(year)2010           -9.267863e-01
as.factor(year)2011           -2.616720e-01
as.factor(year)2012            1.066910e+00
horsepower:torque_levelmedium  6.480368e-02
horsepower:torque_levelhigh    8.361227e-02</code></pre>
</div>
</div>
<p>If we look back up to <span class="math inline">\(2d\)</span>, we see that the intercept and coefficients that we get here are identical to what we got in that problem (for <code>m2</code>). Now let’s do the same for <code>m3</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>X_m3 <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(m3, <span class="at">data =</span> gas_cars_2011) <span class="co"># step 1: define our design matrix, X</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>X_m3_trans <span class="ot">&lt;-</span> <span class="fu">t</span>(X_m3) <span class="co"># step 2: based on our design matrix, define X^t</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>X_m3_2 <span class="ot">&lt;-</span> X_m3_trans <span class="sc">%*%</span> X_m3 <span class="co"># step 3: multiply X^t by our design matrix</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>X_m3_inv <span class="ot">&lt;-</span> <span class="fu">solve</span>(X_m3_2) <span class="co"># step 4: take the inverse of X^t and X</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>y_m3 <span class="ot">&lt;-</span> gas_cars_2011<span class="sc">$</span>highway_mpg <span class="co"># step 5: define y</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>beta_hat_m3 <span class="ot">&lt;-</span> (X_m3_inv <span class="sc">%*%</span> X_m3_trans) <span class="sc">%*%</span> y_m3 <span class="co"># step 6: calculate beta hat, which will be a vector of our coefficients (and intercept)</span></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>beta_hat_m3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                       [,1]
(Intercept)                    43.621168102
horsepower                     -0.085490689
torque_levelmedium            -15.725715370
torque_levelhigh              -21.093956948
height                          0.005608200
length                          0.002385567
width                          -0.006403594
horsepower:torque_levelmedium   0.070409553
horsepower:torque_levelhigh     0.080476781</code></pre>
</div>
</div>
<p>We see again that we get the same result as we did in <code>m3</code> in <span class="math inline">\(2d\)</span>.</p>
</section>
<section id="problem-3---stata" class="level2">
<h2 class="anchored" data-anchor-id="problem-3---stata">Problem 3 - Stata</h2>
<p>Repeat problem 2 parts a. through d.&nbsp;in Stata.</p>
<p><strong>Important</strong>: Repeating part e. (manually estimating&nbsp;β^) in Stata is optional . You can choose to repeat e. for minor extra credit.</p>
<p>Note: Quarto and Stata don't play together well, especially if you're working on Stata remotely. For this problem, and this problem only, you can write a .Do file to answer this question, then include its input and output directly into your submission, by copying the Stata output window and including a non-evaluated chunk</p>
<p>a. The names of the variables in this data are way too long. Rename the columns of the data to more reasonable lengths.</p>
<p>First, the do-file input:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>**part a</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>* <span class="kw">load</span> cars dataset</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>import delimited <span class="st">"C:\Users\dlief\Desktop\cars (1).csv"</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="kw">rename</span> dimensionsheight height</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> dimensionslength <span class="fu">length</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> dimensionswidth <span class="kw">width</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> engineinformationdriveline driveline</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> engineinformationenginetype engine_type</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> engineinformationhybrid hybrid</span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> engineinformationnumberofforward no_fwd_gears</span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> engineinformationtransmission transmission</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> fuelinformationcitympg citympg</span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> fuelinformationfueltype fuel_type</span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> fuelinformationhighwaympg highway_mpg</span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> identificationclassification classification</span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> identificationid id</span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> identificationmake make</span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> identificationmodelyear model_year</span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> identificationyear <span class="fu">year</span></span>
<span id="cb76-21"><a href="#cb76-21" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> engineinformationenginestatistic horsepower</span>
<span id="cb76-22"><a href="#cb76-22" aria-hidden="true" tabindex="-1"></a> <span class="kw">rename</span> v18 torque</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Second, the output:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>. <span class="kw">do</span> <span class="st">"C:\Users\LOCAL_~1\Temp\STD44b0_000000.tmp"</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>. **part a</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>. * <span class="kw">load</span> cars dataset</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>. import delimited <span class="st">"C:\Users\dlief\Desktop\cars (1).csv"</span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>(encoding automatically selected: ISO-8859-1)</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>(18 vars, 5,076 <span class="kw">obs</span>)</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>. </span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a>. <span class="kw">rename</span> dimensionsheight height</span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> dimensionslength <span class="fu">length</span></span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> dimensionswidth <span class="kw">width</span></span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-16"><a href="#cb77-16" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> engineinformationdriveline driveline</span>
<span id="cb77-17"><a href="#cb77-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-18"><a href="#cb77-18" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> engineinformationenginetype engine_type</span>
<span id="cb77-19"><a href="#cb77-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-20"><a href="#cb77-20" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> engineinformationhybrid hybrid</span>
<span id="cb77-21"><a href="#cb77-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-22"><a href="#cb77-22" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> engineinformationnumberofforward no_fwd_gears</span>
<span id="cb77-23"><a href="#cb77-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-24"><a href="#cb77-24" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> engineinformationtransmission transmission</span>
<span id="cb77-25"><a href="#cb77-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-26"><a href="#cb77-26" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> fuelinformationcitympg citympg</span>
<span id="cb77-27"><a href="#cb77-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-28"><a href="#cb77-28" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> fuelinformationfueltype fuel_type</span>
<span id="cb77-29"><a href="#cb77-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-30"><a href="#cb77-30" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> fuelinformationhighwaympg highway_mpg</span>
<span id="cb77-31"><a href="#cb77-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-32"><a href="#cb77-32" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> identificationclassification classification</span>
<span id="cb77-33"><a href="#cb77-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-34"><a href="#cb77-34" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> identificationid id</span>
<span id="cb77-35"><a href="#cb77-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-36"><a href="#cb77-36" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> identificationmake make</span>
<span id="cb77-37"><a href="#cb77-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-38"><a href="#cb77-38" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> identificationmodelyear model_year</span>
<span id="cb77-39"><a href="#cb77-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-40"><a href="#cb77-40" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> identificationyear <span class="fu">year</span></span>
<span id="cb77-41"><a href="#cb77-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-42"><a href="#cb77-42" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> engineinformationenginestatistic horsepower</span>
<span id="cb77-43"><a href="#cb77-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-44"><a href="#cb77-44" aria-hidden="true" tabindex="-1"></a>.  <span class="kw">rename</span> v18 torque</span>
<span id="cb77-45"><a href="#cb77-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-46"><a href="#cb77-46" aria-hidden="true" tabindex="-1"></a>. </span>
<span id="cb77-47"><a href="#cb77-47" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span> <span class="kw">of</span> <span class="kw">do</span>-file</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>